{% set name = "mailbits" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mailbits-{{ version }}.tar.gz
  sha256: 72cd08926b3d0276607a4441ed5a059c4526409d8db2d57e0a6b23996a000bf8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - attrs >=18.1
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - mailbits
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jwodder/mailbits
  summary: Assorted e-mail utility functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
